stages:
  train:
    cmd: python src/train.py
    deps:
    - data/processed/train.csv
    - src/train.py
    - params.yaml
    params:
    - train
    outs:
    - models/model.pkl
    metrics:
    - metrics/train_metrics.json
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - data/processed/test.csv
    - models/model.pkl
    - src/evaluate.py
    metrics:
    - metrics/eval_metrics.json

  # permutation_importance:
  #   cmd: python src/permutation_importance.py
  #   deps:
  #     - data/processed/test.csv
  #     - models/model.pkl
  #     - src/permutation_importance.py
  #   metrics:
  #     - metrics/permutation_importance.json

plots:
- metrics/metrics_history.json:
    x: step
    y:
    - train_accuracy
    - eval_accuracy
    - precision
    - recall
    - f1_score
- metrics/permutation_importance.json:
    template: bar_horizontal
    x: importance_mean
    y: features
